// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVz_jy942WB_3awZgcQ7Sm1S_6SjuB_RQ',
    appId: '1:1085738355311:web:6f55a6c0a0cd7f68285b9a',
    messagingSenderId: '1085738355311',
    projectId: 'silence-v6',
    authDomain: 'silence-v6.firebaseapp.com',
    storageBucket: 'silence-v6.firebasestorage.app',
    measurementId: 'G-P5LCD9583D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvuVu4AmLjxglvwcsf3UwMo82YsjQmLsY',
    appId: '1:1085738355311:android:b1f82d4c4d36e0b8285b9a',
    messagingSenderId: '1085738355311',
    projectId: 'silence-v6',
    storageBucket: 'silence-v6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc13xl3KelrvwEojfFhV4wJR9Y3ygFqQA',
    appId: '1:1085738355311:ios:049d0919a8e5b5d3285b9a',
    messagingSenderId: '1085738355311',
    projectId: 'silence-v6',
    storageBucket: 'silence-v6.firebasestorage.app',
    iosBundleId: 'com.silence.app.silence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc13xl3KelrvwEojfFhV4wJR9Y3ygFqQA',
    appId: '1:1085738355311:ios:049d0919a8e5b5d3285b9a',
    messagingSenderId: '1085738355311',
    projectId: 'silence-v6',
    storageBucket: 'silence-v6.firebasestorage.app',
    iosBundleId: 'com.silence.app.silence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVz_jy942WB_3awZgcQ7Sm1S_6SjuB_RQ',
    appId: '1:1085738355311:web:03f098c618cb1536285b9a',
    messagingSenderId: '1085738355311',
    projectId: 'silence-v6',
    authDomain: 'silence-v6.firebaseapp.com',
    storageBucket: 'silence-v6.firebasestorage.app',
    measurementId: 'G-DG5C88MXPN',
  );
}
